### ISSUE TITLE
@davewthompson which image?  The most common reason for this error occurs when you try to boot a really really old 3.8.13 image with a newer BBB with an eMMC based off the 5.1* spec.. Which i fixed on Jun 15, 2016.

### ISSUE THREAD

**Issue by awadhesh39** [RobertCNelson/boot-scripts#106]
@davewthompson which image?  The most common reason for this error occurs when you try to boot a really really old 3.8.13 image with a newer BBB with an eMMC based off the 5.1* spec.. Which i fixed on Jun 15, 2016. 

If you show me the full serial boot log i can verify what issue you have..

```code
 * Micron/Kingston/<insert eMMC manufacture>, eol products on a quarterly basis.
```

Regards,

_Originally posted by @RobertCNelson in https://github.com/RobertCNelson/boot-scripts/issues/89#issuecomment-440847404_

**Comment by awadhesh39** [comment]
I want to know is there any patches or fixes in old kernel version 3.18 and u-boot v2013 so that I can fix this issue without replacing my whole kernel and u-boot code.

**Comment by RobertCNelson** [comment]
@awadhesh39 patches: This was fixed with 3.8.13-bone80

hints on how to fix are listed here:

https://gist.github.com/RobertCNelson/39faf80ddc9fcefae74dce2c6ca2eb45

Regards,

**Comment by RobertCNelson** [comment]
@awadhesh39 

```
Hi, in which directory should I run 'git clone https://github.com/RobertCNelson/yakbuild' inside kernel directory?

In case this script has to run in independent directory then how apply to our kernel source tree.
```

**Comment by RobertCNelson** [comment]
@awadhesh39 

I tried to run above steps with following error:

CC credential-cache.o
In file included from http.c:1:0:
http.h:6:23: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>
^
compilation terminated.
make: *** [http.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from http-walker.c:4:0:
http.h:6:23: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>
^
compilation terminated.
make: *** [http-walker.o] Error 1
In file included from http-fetch.c:3:0:
http.h:6:23: fatal error: curl/curl.h: No such file or directory
#include <curl/curl.h>
^
compilation terminated.
make: *** [http-fetch.o] Error 1

Can you please elaborate more how to do it. I am using kernel version: 3.8.13-00745-g6e0b32d-dirty hence I used this version in pace of 3.8.13-boneWXYZ.

**Comment by RobertCNelson** [comment]
> Hi, in which directory should I run 'git clone https://github.com/RobertCNelson/yakbuild' inside kernel directory?

Where ever you want.

**Comment by RobertCNelson** [comment]
> curl/curl.h

https://packages.debian.org/search?suite=buster&searchon=contents&keywords=curl%2Fcurl.h

libcurl4-gnutls-dev

**Comment by RobertCNelson** [comment]
@awadhesh39 

> Can you please elaborate more how to do it. I am using kernel version: 3.8.13-00745-g6e0b32d-dirty hence I used this version in pace of 3.8.13-boneWXYZ.

"3.8.13-00745-g6e0b32d-dirty" is NOT one of my official releases..

Grab these two patches and rebuild your "custom" build..

https://raw.githubusercontent.com/RobertCNelson/bb-kernel/am33x-v3.8/patches/emmc/0001-mmc-core-Update-the-ext-csd.rev-check-for-eMMC5.1.patch
https://raw.githubusercontent.com/RobertCNelson/bb-kernel/am33x-v3.8/patches/emmc/0002-mmc-Allow-forward-compatibility-for-eMMC.patch
