### ISSUE TITLE
What script to flash Green Gateway?

### ISSUE THREAD

**Issue by JoseGoncalves** [RobertCNelson/boot-scripts#120]
There is no flasher script specific for the Green Gateway. Wouldn't be better to have one?

I think that the script for the Green Wireless (`init-eMMC-flasher-v3-bbgw.sh`) would work (did not try it yet), with the exception of the EEPROM programming stuff, which is only called if the board's EEPROM is corrupted.

BTW, [SeeedStudio wiki](https://wiki.seeedstudio.com/BeagleBone-Green-Gateway/) is indicating to use the generic BBB flasher script (`init-eMMC-flasher-v3.sh`), which will not be successful on the Green Wireless and Green Gateway boards.

**Comment by RobertCNelson** [comment]
@JoseGoncalves , just use the generic one..

During the Green Wireless development, we used the onboard eeprom to store a unique mac address for the wl18xx..

About a year later, we discovered the wl18xx had it's own unique mac address stored internally, it could be used as long as you told the wl18xx to use 00:00:00:00:00:00.

So today, on all w18xx devices we force 00:00:00:00:00:00 and everything works great..

Regards

**Comment by JoseGoncalves** [comment]
@RobertCNelson I remember that when I start to flash BB Green Wireless devices a couple of months ago the generic script did not work and I needed to use the specific one (`init-eMMC-flasher-v3-bbgw.sh`). I'm going to try this again, both in Wireless and in Gateway, to see if it works now.

**Comment by JoseGoncalves** [comment]
I've tested and confirm that both Green Wireless and Green Gateway can be flashed with the generic flasher script.
Thanks @RobertCNelson
