### ISSUE TITLE
mjpg-streamer stops working when using libroboticscontrol example

### ISSUE THREAD

**Issue by ninjatrent** [RobertCNelson/boot-scripts#121]
mjpg-streamer stops working when using the rc_test_motors.c example from libroboticscontrol. Camera is active on boot and works when I enter " rc_test_motors -d 0.5 " but stops when motors are reversed with " rc_test_motors -d -0.5 ".

**Comment by RobertCNelson** [comment]
@ninjatrent this is probally a power surge on the usb bus..

You should post it here:

https://github.com/beagleboard/librobotcontrol/issues

But software-wise i don't see how we can fix this..

Regards,

**Comment by ninjatrent** [comment]
It does appear to be an issue with power on the USB bus. The video stream freezes and the cam shuts off when anything over 0.3 duty is issued. Tried a lower duty and camera remains on. It's strange that this didn't occur in previous use. I've been using with the BBB W and Robotics Cape. Thank you for the quick response.
