### ISSUE TITLE
bbb-eMMC-flasher-eewiki-ext4 not working on ti-linux-rt-4.4.y kernel

### ISSUE THREAD

**Issue by hegyibalint** [RobertCNelson/boot-scripts#20]
With ti-linux-kernel-dev repo ti-linux-rt-4.4.y branch, the bbb-eMMC-flasher-eewiki-ext4.sh script stopped working.

The following happens:
```
debian@arm:/opt/scripts/tools/eMMC$ sudo ./bbb-eMMC-flasher-eewiki-ext4.sh
-----------------------------
Version: [1.20160113: upgrade backup u-boot: v2016.01-r5...]
-----------------------------
Checking for Valid BBB EEPROM header
debian@arm:/opt/scripts/tools/eMMC$
```

------------------------------

After debugging the script I found a solution:

bbb-eMMC-flasher-eewiki-ext4.sh line 118:
`eeprom_location=$(ls /sys/devices/ocp*/44e0b000.i2c/i2c-0/0-0050/eeprom 2> /dev/null)`

It seems the `ocp` directory is moved from `/sys/devices/ocp` to `/sys/devices/platform/ocp`.
After correcting the path, the flasher script worked perfectly.

Anybody can validate this?

**Comment by RobertCNelson** [comment]
Nice catch @hegyibalint !

I had not tested flashing v4.4.x yet..  What happened behind the scenes, with v4.1.x+ we've been using nvmem which has a new eeprom location, however the latest version puts it back where it use to be under eeprom for compatibility sake..

Regards,
