### ISSUE TITLE
Can't clone SD card to eMMC

### ISSUE THREAD

**Issue by dna5589** [RobertCNelson/boot-scripts#21]
I've tried the "init-emmc-flasher-v3-bbg.sh" while adding the required "cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3-bbg.sh" to /boot/uEnv.txt and it seems to skip over this and boot up normally without ever copying files over to the eMMC.
I've also tried running the "sudo ./bbb-eMMC-flasher-eewiki-ext4.sh" to clone the SD card over to the eMMC but I end up with the following error:

```
-----------------------------
Starting eMMC Flasher from microSD media
Version: [1.20160222: deal with v4.4.x+ back to old eeprom location...]
-----------------------------
Checking for Valid bbg-eeprom header
Valid bbg-eeprom header found [335]
-----------------------------
copying: [/dev/mmcblk0] -> [/dev/mmcblk1]
lsblk:
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
mmcblk0     179:0    0   1.9G  0 disk 
└─mmcblk0p1 179:1    0   1.9G  0 part /
-----------------------------
df -h | grep rootfs:
-----------------------------
Error: [/dev/mmcblk1] does not exist
writing to [/dev/mmcblk1] failed...
```

I'm not sure if I'm not putting the files in the right places or not setting the options up correctly

**Comment by RobertCNelson** [comment]
So where is "/dev/mmcblk1"
```
cat /boot/uEnv.txt | grep dtb
```

**Comment by dna5589** [comment]
the "cat" doesn't return anything. I never had to add a dtb related line in my uEnv.txt before. Could be my problem then
I assume /dev/mmcblk1 isn't being mounted because it is booting off of the SD card and doesn't mount the eMMC at the same time?

**Comment by RobertCNelson** [comment]
lsblk show's all the block devices, (doesn't matter about mount situation)

So either you didn't boot a base image with the eMMC support, or didn't load the eMMC overlay...

Regards,

**Comment by dna5589** [comment]
I'll look into those more then. 

Thanks for your help, Robert. I appreciate it

**Comment by dna5589** [comment]
All set. Was trying to use an LCD7 and there were pin conflicts with the eMMC. Had to modify the LCD7 dts, recompile, and rebuild the kernel. When I got both loading together the script worked perfectly.
