### ISSUE TITLE
BBB flash from eMMC to SD not running completely

### ISSUE THREAD

**Issue by julianhille** [RobertCNelson/boot-scripts#25]
Scripts exits with error code 32 in line 398 due to an umount command of a directory which is not mounted.

Umount of a directory which is not mounted:
https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh#L398

It seems like a copy and paste error from  https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/init-eMMC-flasher-v3.sh

But there is a tmpfs mounted in line [47](It seems like a copy and paste error from  https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/init-eMMC-flasher-v3.sh#L47) which is missing in BBB flasher.

I was not sure how to fix it, if i had to add a mount to a tmpfs or remove the umount of temp.

**Comment by RobertCNelson** [comment]
thanks @julianhille , yeah let's just nuke the /tmp/ umount..  All the scripts in ./tools/eMMC/ are copy's of each other with unique tweaks. that /tmp/ is really for any of the "init-xyz" variations...

**Comment by julianhille** [comment]
Thank you for the fast response.

Robert Nelson <notifications@github.com> schrieb am Fr., 10. Juni 2016
18:19:
