### ISSUE TITLE
eMMC to SD scripts

### ISSUE THREAD

**Issue by julianhille** [RobertCNelson/boot-scripts#26]
The halt -f command does not seem to be right in eMMC -> to SD direction does it?

For what reason should i stop the cpu and halt everything?
Can we remove these lines from the scripts?

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh#L409

**Comment by RobertCNelson** [comment]
hi @julianhille another old line, now removed.. ;)
