### ISSUE TITLE
because of udev rules flasher / image is not reusable

### ISSUE THREAD

**Issue by julianhille** [RobertCNelson/boot-scripts#27]
The script is not reusable as the boot script creates a new net persistent udev rule each boot, if the script is used in more than one beagle bone.

Interface scripts do not work if they rely on eth0.

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/init-eMMC-flasher-v3.sh

**Comment by RobertCNelson** [comment]
Please explain a little more, as this should be taken care of by:

https://github.com/RobertCNelson/omap-image-builder/blob/master/tools/setup_sdcard.sh#L1356-L1366

Regards,

**Comment by julianhille** [comment]
When does this file evers called?

- setup a new bbb with a debian base image and provision it.
- exec a beaglebone-black-make-microSD-flasher-from-eMMC.sh and have an image flashed to the SD
- put the sd card into two bbb and let it auto flash
 
after looking at the sd card and mount it the udev file is filled with different persistent data.

Where should the setup_sdcard.sh be called?

**Comment by RobertCNelson** [comment]
Which base image?

If it's from eewiki.net, the directions are right here:

https://eewiki.net/display/linuxonarm/BeagleBone+Black#BeagleBoneBlack-Networking:UsingasharedSDcardwithMultipleBeagleBone

If it's the netinstall, you need to do ^ manually..

If it's from elinux.org, it's automaticly setup..

Regards,

**Comment by julianhille** [comment]
its a ready to use image. I guess my mistake is that i delete the udev rule in my provisioning.

**Comment by julianhille** [comment]
This is an issue i created myself. Thank you for your help.
