### ISSUE TITLE
Can't find /tmp/rootfs/boot/uEnv.txt when  Extracting eMMC contents

### ISSUE THREAD

**Issue by popjxc** [RobertCNelson/boot-scripts#40]
I am extracting eMMC contents to sdCard on my BBB,  when running the sell:
 sudo /opt/scripts/tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh

I got a error:
 sed: can't read /tmp/rootfs/boot/uEnv.txt: No such file or directory

Any helps? 
Thanks!

**Comment by popjxc** [comment]
Maybe my BBB too old, it is bone40, I copy one from bone79, and it works for me.

**Comment by rohitsay89** [comment]
I am getting the same error when I run the script, I do not want to change my kernel or update my file system version. Currently I am using kernel 3.8.13bone53 with ubuntu 14.04, also if I do a git pull in /opt/scripts, I face lot of new issues so updating the script is not an option for me. Any help would be appreciated.
Thanks,
Rohit
