### ISSUE TITLE
Latest beaglebone-black-make-microSD-flasher-from-eMMC.sh

### ISSUE THREAD

**Issue by leearmstrong** [RobertCNelson/boot-scripts#45]
I have just used the beaglebone-black-make-microSD-flasher-from-eMMC.sh script as I have done many times before but did a git pull before hand to grab the latest code.  

The script runs fine with no problems and creates an SD card that is bootable.  However this then seems to just boot into the SD Card and not a flasher.  No cylon LED's and no flashing of the eMMC appears to be taking place at all.

To fix I went into the booted clone and found that in the /boot/uEnv.txt the script was disabled and had a # before it.  I removed this and it seemed to then boot into the flasher

@RobertCNelson

**Comment by RobertCNelson** [comment]
HI @leearmstrong strange...

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh#L212-L216

What image did you start with? cat /etc/dogtab

and i'll try to replicate it this morning..

Regards,

**Comment by leearmstrong** [comment]
Yeah it is weird, I managed to work around it but strange it didn't set the uEnv boot script.

Anyways...

```
root@test:~# cat /etc/dogtag
BeagleBoard.org Debian Image 2015-10-04
```

**Comment by leearmstrong** [comment]
FYI here is the uEnv.txt after running and creating the SD card...

```
root@planefinder-radar:~# cat /boot/uEnv.txt 
#Docs: http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

uname_r=4.1.15-ti-r41
dtb=am335x-boneblack-emmc-pf-overlay-pps.dtb

cmdline=coherent_pool=1M quiet

#cmdline=init=/opt/scripts/tools/eMMC/init-eMMC-flasher-v3.sh
#uuid=6cda2a23-fb81-4c2d-a41c-2e9c4ec39f5d
uuid=83fb7a6e-cc81-4947-ad63-acbc2c20f371
```

The SD card then works by allowing the init-eMMC-flasher to work

**Comment by RobertCNelson** [comment]
I see the issue, with the function refactor  some assumptions are made...

**Comment by RobertCNelson** [comment]
@leearmstrong i've reworked things and ran a couple runs, it's working after:

https://github.com/RobertCNelson/boot-scripts/compare/7ac151daee228579acfe075b9d1160d8c72844c0...29818f58089738be81ca186551c8f8e3ec9cf58c

Regards,

**Comment by leearmstrong** [comment]
Brilliant. Thanks!
