### ISSUE TITLE
SoftAp0 causes wrong DNS resolution

### ISSUE THREAD

**Issue by hongquan** [RobertCNelson/boot-scripts#55]
I'm using Ubuntu image for BeagleBone Black.
Because of this script _/opt/scripts/boot/am335x_evm.sh_, the file /etc/dnsmasq.d/_SoftAp0_ is added and makes every domain translated to 172.1.8.1!
This breaks `apt`.

**Comment by RobertCNelson** [comment]
Sorry @hongquan it's now fixed:

https://github.com/RobertCNelson/boot-scripts/commit/09ae22ec483e5483c6ae7f0ca7bbbabf864b06af

i'm not sure when that was added, or the fact when connman was installed, it would just work..  But in the ubuntu images without connman installed things break..

Regards,

**Comment by hongquan** [comment]
Thanks for the fix.
