### ISSUE TITLE
beaglebone-black-eMMC-flasher.sh fails on Debian 8.7 2017-03-19 4GB SD IoT image from beaglebone.org

### ISSUE THREAD

**Issue by clolsonus** [RobertCNelson/boot-scripts#56]
When running the /opt/script/tools/beaglebone-black-eMMC-flasher.sh script, I am getting the message:

    "Error: script halting, system unrecognized..."

This is with the beaglebone.org recommended image: Debian 8.7 2017-03-19 4GB SD IoT
I have cd'd to /opt/script/tools and run git pull to make sure I have the freshest version of the scripts.

Diving into the script code: lines 32-33 determine the boot drive by using the lsblk command.  However, lsblk -l doesn't output what the script is looking for.  There has been a change somewhere (in the lsblk command output, or the default layout of the system partitions?)
Because the boot drive can't be determined by the lsblk method on this newest system, the script fails.

There are probably other ways to detect the boot drive, but maybe not as robustly?  This is a handy script for cloning beaglebone images when a person has a few beaglebones to manage and keep up to date, so it's something I'd love to continue to be able to use (without having to resort to horrible local hacks.) :-)

Thanks,

Curt.

**Comment by RobertCNelson** [comment]
@clolsonus this issue is documented in the "readme.txt" is the same directory:

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/readme.txt

```
WARNING: Do not use:

beaglebone-black-eMMC-flasher.sh
init-eMMC-flasher.sh

They are only in this directory for support of the Ancient 2014 release.
```

The script you really want to run is above in ./eMMC/

likewise documented in the readme.md

Regards,

**Comment by clolsonus** [comment]
Ok, thanks for the quick clarification.

**Comment by RobertCNelson** [comment]
you were actually the 2nd person to ask me about this today, when wheezy goes eol, i'll be able to nuke that old script. ;)
