### ISSUE TITLE
WIFI AP

### ISSUE THREAD

**Issue by nivoset** [RobertCNelson/boot-scripts#58]
Ok, im trying to figure out where this is happening, but on start up it constantly sets the wifi back to BeagleBone-xxxx for the access point, even if i comment out the section in am335x_evm.sh am i missing a second place?

this is a little more frustrating as its also decided to not let me enable tethering afterwords (Tethering not supported for wifi)

This is on a BBGW

root@beaglebone:/boot/dtbs# cat /etc/debian_version
8.7
root@beaglebone:/boot/dtbs# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

I had fixed this before by doing a delayed command to just force it back to what i wanted... but i copied the SD card and it no longer works (that part confuses me more)

**Comment by RobertCNelson** [comment]
@nivoset so the wifi access point is controlled via:

/etc/default/bb-wl18xx

to disable everything, just set:

TETHER_ENABLED=no

and you'll be free to setup everything yourself

(here's the whole list of options: https://github.com/rcn-ee/repos/blob/master/bb-wl18xx-firmware/suite/jessie/debian/postinst#L20-L46 ) 

Regards,

**Comment by nivoset** [comment]
not quite what i want. i want it to tether, just with my information in it,
not the default. id be fine without it ever touching it. but i will find
out something

**Comment by RobertCNelson** [comment]
@nivoset 

Then your looking at: /etc/default/bb-wl18xx

```
USE_PERSONAL_SSID="BeagleBone"
USE_PERSONAL_PASSWORD="BeagleBone"
USE_APPENDED_SSID=yes
```
Regards,

**Comment by nivoset** [comment]
Thank you, i was looking for where those settings were for a while and couldn't find them
