### ISSUE TITLE
Please allow option to disable boot-scripts control of networking/DNS

### ISSUE THREAD

**Issue by cyrilcros** [RobertCNelson/boot-scripts#63]
Hi,
I am trying to install pi-hole on the BBB. Unfortunately, scripts like am335x_evm.sh make strong assumptions  about what kind of DNS services I want to set up and auto-generate at boot a conflicting dnsmasq configuration file 'SoftAp0'.

Could you please think about using some configuration file that allows me to override these kind of behaviors and use my own choice of DHCP or DNS servers? Maybe add a script to get rid of the bonescript server / DHCP connections over USB? I can always edit out things but this could be cleaner.

Thanks for your work!

**Comment by RobertCNelson** [comment]
Sure, i'll add a /etc/default/bb-boot and split out parts of that script to easily enable/disable things.
