### ISSUE TITLE
Proper way to disable the getting_started image.

### ISSUE THREAD

**Issue by ycdtosa** [RobertCNelson/boot-scripts#67]
Hi. I would like to have control of the image file loaded when the BB is plugged via USB.
That control would ideally allow me to disable the feature entirely.

so here is the question:

What is the proper way to disable loading the image file, if any?
Also, it feels safe to just remove the image files. Am i right?
Would that be enough?

Also, I am aware of issue #63, and i would not mind working on that.

having  /etc/default/bb-boot
(  content is uppercase just like /etc/default/bb-wl18xx )
<pre>
# USB_IMAGE_FILE_DISABLED
# default value <empty> which means the usb_image_file will be loaded.
# expected values "yes" to disable loading the image_file.
USB_IMAGE_FILE_DISABLED=yes
</pre>

and maybe
<pre>
# USE_USB_IMAGE_FILE=/full/path/to/image/file.img
# set the path to the file that should be loaded.
# if the file does not exist, an error will be logged unless USB_IMAGE_FILE_DISABLED=yes
# any auto-detected value will be ignored and this one will be used instead, if present.
</pre>

For what i have seen so far, most of the work is done at the am335x_evm.sh script. 
and it has to do with the usb_image_file variable in that file.

IIUC the variable value is being changed based on board detected,
and the default value of usb_image_file is discarded,

Those values can be (auto-detected) to any of the following:
/var/local/bb_usb_mass_storage.iso | .img
/var/local/bbg_usb_mass_storage.iso | .img
/var/local/bbgw_usb_mass_storage.iso | .img

it will finally log the selected file.
from there use_libcomposite() takes care of the rest....

So i would not change anything until use_libcomposite()
there i would check those to variables and use them if these are set.

**Comment by RobertCNelson** [comment]
@ycdtosa yeah i forgot about this... let's start hacking on it.. ;)

**Comment by ycdtosa** [comment]
i have already a clone repo with that purpose...
still there are a few things i would like to know...

like...
where is /etc/default/bb-wl18xx?
is it in a different repository?

so i can add the /etd/default/bb-boot config file there too.

**Comment by RobertCNelson** [comment]
I just added it locally.., in omap-image-builder i'll move it..
