### ISSUE TITLE
eMMC has been flashed: please wait for device to power down. but no powerdown

### ISSUE THREAD

**Issue by ycdtosa** [RobertCNelson/boot-scripts#70]
bbb-eMMC-flasher-eewiki-ext4.sh seems to work,
and ends with the message "eMMC has been flashed: please wait for device to power down"
but there is no attempt to power down the machine.

maybe the message should be changed to...
"eMMC has been flashed: you might power down / halt the device now"

**Comment by RobertCNelson** [comment]
Yeah, shutdown is called, depending on kernel/etc it's pretty random if it shuts down..

**Comment by ycdtosa** [comment]
The message is shown by copy_rootfs()
at https://github.com/RobertCNelson/boot-scripts/blob/master/tools/eMMC/bbb-eMMC-flasher-eewiki-ext4.sh#L266

which is called from two places:
at 389 and 431

but i dont see no halt or shutdown afterwards

**Comment by ycdtosa** [comment]
BTW: I am calling the script by hand, and i dont mind if it does not shutdown...
in fact i want to run another script later, so i rather have it without the shutdown.

user can decide if he wants to shutdown... it is just that currently the message is wrong, since it does not match what the script does, AFAICT.

**Comment by RobertCNelson** [comment]
Yeah, i guess it doesn't..  At one point it probally did.  But that was back when all the scripts where clones of each other, before the introduction of the functions.sh option..

**Comment by ycdtosa** [comment]
yeap. this one does not seem to use the functions.sh file at all.

**Comment by ycdtosa** [comment]
I would just change the message and close the issue. :-)
