### ISSUE TITLE
Simple Readme

### ISSUE THREAD

**Issue by RGB-123** [RobertCNelson/boot-scripts#8]
Any chance you have a simple readme on this script?  I tried running everything, but wasn't sure when if it completed.  Cylon leds ran without stopping.  Using ftdi terminal it appears that it completed, but when I pulled card and tried to install on another BBB no luck.

**Comment by RobertCNelson** [comment]
Oh it depends on a bunch of things, so i'd rather users ask before they try to use it.. ;)

Which script are you running?
What Board model?
What's your current rootfs layout (partitions/etc... fdisk -l)
What version (cat /etc/dogtag)

Regards,

**Comment by RGB-123** [comment]
Robert, (*noob warning here*).  Basically, I take a fresh BBB Rev C (BeagleBoard.org BeagleBone Debian Image 2014-04-23), install this repo (https://github.com/Yona-Appletree/LEDscape), which requires some mods (see readme) to allow full use of the prus and turning off the HDMI.  I then simply want to clone the entire image to make it easy to install on multiple BBBs.  The BBB and this repo get used alot for controlling leds.  Pretty simple really.

```
Disk /dev/mmcblk0: 3925 MB, 3925868544 bytes
4 heads, 16 sectors/track, 119808 cylinders, total 7667712 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

        Device Boot      Start         End      Blocks   Id  System
/dev/mmcblk0p1   *        2048      198655       98304    e  W95 FAT16 (LBA)
/dev/mmcblk0p2          198656     7667711     3734528   83  Linux

Disk /dev/mmcblk0boot1: 1 MB, 1048576 bytes
4 heads, 16 sectors/track, 32 cylinders, total 2048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

Disk /dev/mmcblk0boot1 doesn't contain a valid partition table

Disk /dev/mmcblk0boot0: 1 MB, 1048576 bytes
4 heads, 16 sectors/track, 32 cylinders, total 2048 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk identifier: 0x00000000

Disk /dev/mmcblk0boot0 doesn't contain a valid partition table

**Comment by RobertCNelson** [comment]
I was afraid it was that old image, things get pretty fun with that old boot layout. (bb.org had me change things in July 2014).  Calling the "./tools/beaglebone-black-eMMC-flasher.sh" should work (ingore the name, it works both directions)... Make sure to un-commit this line i just pushed: 

https://github.com/RobertCNelson/boot-scripts/blob/master/tools/beaglebone-black-eMMC-flasher.sh#L213

as then it'll add the file used to give a hint to the init script to flash the eMMC..

"it" should still work, but if it fails there should be a log under /boot/uboot/ (the new july 2014 layout auto logs everything to serial/hdmi/etc.. the old may 2014 was a pain to debug..)

Regards,

**Comment by RGB-123** [comment]
Robert, thanks for the FYSA.  I have no problem updating to the latest image if this will fix things.  It looks like there is a 2015-03-01 release.  Can you confirm if this will work with your scripts?  Otherwise July 2014 is fine with me.  We need to get all the board manufs with the latest images!  Thanks for all your help.

**Comment by RobertCNelson** [comment]
Correct, with the newer image, (anything after July/August 2014) so the official (2015-03-01) you can just run "./tools/eMMC/beaglebone-black-make-microSD-flasher-from-eMMC.sh"

**Comment by RobertCNelson** [comment]
I should add, after that change in July, we are more able to protect the board from new users accidentally deleting the boot files, so they have a better out of box experience. and i have on plans on changing it again, it's just too disruptive...  ;)

http://elinux.org/Beagleboard:U-boot_partitioning_layout_2.0

Regards,

**Comment by RGB-123** [comment]
Robert, thanks for all your help.  I'll be sure to tell Jadon, too!  I'll probably throw up a quick blog post and tweet about the need to update.  I flashing new image now to SD and will report back on how things went.  Fingers Crossed!

**Comment by RGB-123** [comment]
Robert, I am making progress here.  I had a couple of quick questions about the location of the .dtb files in the latest image.  I have been using our LEDscape repo to modify the .dtb file locations to handle the control of the prus to enable 48 parallel outputs for the control of leds.  Normally, I would follow one of the procedures below, but for this new image it seems the .dtb file locations have changed.  Can you point me to any documentation about where they might reside and any changes made in regard to the .dtb functionality?

PS I posted this on the google groups (sorry to trouble you)  - https://groups.google.com/forum/#!category-topic/beagleboard/beaglebone-black/tC6Jo-nc6QI

Angstrom - RevB
```
git clone git://github.com/Yona-Appletree/LEDscape
cd LEDscape
cp /boot/am335x-boneblack.dtb{,.preledscape_bk}
cp am335x-boneblack.dtb /boot/
modprobe uio_pruss
reboot
```
Debian - RevC
```
git clone git://github.com/Yona-Appletree/LEDscape
cd LEDscape
cp /boot/uboot/dtbs/am335x-boneblack.dtb{,.preledscape_bk}
cp am335x-boneblack.dtb /boot/uboot/dtbs/
modprobe uio_pruss
```

**Comment by RGB-123** [comment]
Robert, great news.  I was able to use your script without a problem when the 2015-03-01 image was installed.  Trouble is that I have a stack of 25 BBBs with 2014-05 (May) images.  When I tried using the flasher with these old images I didn't have any luck.  

In summary, is there an easy way to go from 2014-05 image to custom 2015-03-01 image, without having to do the intermediary step of flashing 2015-03-01?

**Comment by RobertCNelson** [comment]
Oh, you'll have to do the hold down "boot" button, plug in power, wait for 4 led's, lift up finger-nail on boot button trick.  As the custom flasher script doesn't add the "old u-boot in eMMC" compatibility "uEnv.txt"...  I need to add that..

**Comment by RGB-123** [comment]
Robert, awesome!  That did the trick.  I've gotten use to the fancy new images. Thanks again for all your help!
