### ISSUE TITLE
Cannot boot from SDcard on BBB rev. A5A board

### ISSUE THREAD

**Issue by woopla** [RobertCNelson/boot-scripts#92]
Hello,

I'm resurrecting an A5A rev. board that boots fine to Angstrom Linux on the 2GB eMMC.

I've tried the latest 'small image' versions of Debian and Ubuntu:
- `bone-debian-9.9-console-armhf-2019-05-12-1gb.img.xz`
- `bone-ubuntu-18.04.2-console-armhf-2019-04-10-2gb.img.xz`

I used `xzcat <image> | dd of=/dev/sda` to write both. And neither can boot, I get the following on the serial port:
```shell
U-Boot SPL 2019.04-00002-gc8b5ad3a1f (Apr 16 2019 - 09:21:31 -0500)
Trying to boot from MMC1
Loading Environment from EXT4... ** No partition table - mmc 0 **
```

I tried on several SDHC cards to no avail.

Seems that the bootloader is getting confused between MMC1 and MMC0. I can't even get to the u-boot boot menu. I renamed the MLO file on the eMMC, so I can't even boot from the eMMC anymore.

Any pointers to how I can fix this?

Thanks,

Clément

**Comment by RobertCNelson** [comment]
@woopla,

Those images work fine for me.. ( bone-debian-9.9-console-armhf-2019-05-10-2gb.img.xz )

Angstrom is not supported..

```
U-Boot SPL 2019.04-00002-gc8b5ad3a1f (Apr 16 2019 - 09:21:31 -0500)
Trying to boot from MMC1
Loading Environment from EXT4... ** File not found /boot/uboot.env **

** Unable to read "/boot/uboot.env" from mmc0:1 **


U-Boot 2019.04-00002-gc8b5ad3a1f (Apr 16 2019 - 09:21:31 -0500), Build: jenkins-github_Bootloader-Builder-116

CPU  : AM335X-GP rev 2.0
I2C:   ready
DRAM:  512 MiB
No match for driver 'omap_hsmmc'
No match for driver 'omap_hsmmc'
Some drivers were not found
Reset Source: Power-on reset has occurred.
RTC 32KCLK Source: External.
MMC:   OMAP SD/MMC: 0, OMAP SD/MMC: 1
Loading Environment from EXT4... ** File not found /boot/uboot.env **

** Unable to read "/boot/uboot.env" from mmc0:1 **
Board: BeagleBone Black
<ethaddr> not set. Validating first E-fuse MAC
BeagleBone Black:
BeagleBone: cape eeprom: i2c_probe: 0x54:
BeagleBone: cape eeprom: i2c_probe: 0x55:
BeagleBone: cape eeprom: i2c_probe: 0x56:
BeagleBone: cape eeprom: i2c_probe: 0x57:
Net:   eth0: MII MODE
cpsw, usb_ether
Press SPACE to abort autoboot in 2 seconds
board_name=[A335BNLT] ...
board_rev=[0A5A] ...
switch to partitions #0, OK
mmc0 is current device
SD/MMC found on device 0
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:1...
gpio: pin 56 (gpio 56) value is 0
gpio: pin 55 (gpio 55) value is 0
gpio: pin 54 (gpio 54) value is 0
gpio: pin 53 (gpio 53) value is 1
switch to partitions #0, OK
mmc0 is current device
gpio: pin 54 (gpio 54) value is 1
Checking for: /uEnv.txt ...
Checking for: /boot.scr ...
Checking for: /boot/boot.scr ...
Checking for: /boot/uEnv.txt ...
gpio: pin 55 (gpio 55) value is 1
2278 bytes read in 71 ms (31.3 KiB/s)
Loaded environment from /boot/uEnv.txt
Checking if uname_r is set in /boot/uEnv.txt...
gpio: pin 56 (gpio 56) value is 1
Running uname_boot ...
loading /boot/vmlinuz-4.14.108-ti-r104 ...
9925120 bytes read in 673 ms (14.1 MiB/s)
debug: [enable_uboot_overlays=1] ...
debug: [enable_uboot_cape_universal=1] ...
debug: [uboot_base_dtb_univ=am335x-boneblack-uboot-univ.dtb] ...
uboot_overlays: [uboot_base_dtb=am335x-boneblack-uboot-univ.dtb] ...
uboot_overlays: Switching too: dtb=am335x-boneblack-uboot-univ.dtb ...
loading /boot/dtbs/4.14.108-ti-r104/am335x-boneblack-uboot-univ.dtb ...
162891 bytes read in 100 ms (1.6 MiB/s)
uboot_overlays: [fdt_buffer=0x60000] ...
uboot_overlays: loading /lib/firmware/BB-BONE-eMMC1-01-00A0.dtbo ...
1440 bytes read in 77 ms (17.6 KiB/s)
uboot_overlays: loading /lib/firmware/BB-HDMI-TDA998x-00A0.dtbo ...
4896 bytes read in 765 ms (5.9 KiB/s)
uboot_overlays: loading /lib/firmware/BB-ADC-00A0.dtbo ...
711 bytes read in 418 ms (1000 Bytes/s)
uboot_overlays: loading /lib/firmware/AM335X-PRU-UIO-00A0.dtbo ...
883 bytes read in 773 ms (1000 Bytes/s)
loading /boot/initrd.img-4.14.108-ti-r104 ...
4425686 bytes read in 344 ms (12.3 MiB/s)
debug: [console=ttyO0,115200n8 bone_capemgr.uboot_capemgr_enabled=1 root=/dev/mmcblk0p1 ro rootfstype=ext4 rootwait coherent_pool=1M net.ifnames=0 quiet cape_universal=enable] ...
debug: [bootz 0x82000000 0x88080000:4387d6 88000000] ...
## Flattened Device Tree blob at 88000000
   Booting using the fdt blob at 0x88000000
   Loading Ramdisk to 8fbc7000, end 8ffff7d6 ... OK
   Loading Device Tree to 8fb3b000, end 8fbc6fff ... OK

Starting kernel ...

[    0.002142] timer_probe: no matching timers found
[    0.955162] wkup_m3_ipc 44e11324.wkup_m3_ipc: could not get rproc handle
[    1.258982] omap_voltage_late_init: Voltage driver support not added
[    1.266023] PM: Cannot get wkup_m3_ipc handle
[    1.464497] hdmi-audio-codec hdmi-audio-codec.1.auto: ASoC: no source widget found for Playback
[    1.473468] hdmi-audio-codec hdmi-audio-codec.1.auto: ASoC: Failed to add route Playback -> direct -> TX

Debian GNU/Linux 9 arm ttyS0

rcn-ee.net console Debian Image 2019-05-10

Support/FAQ: http://elinux.org/BeagleBoardDebian

default username:password is [debian:temppwd]

arm login:
```
Regards,

**Comment by woopla** [comment]
I don't want Angstrom anymore, that's why I'm trying to boot from the Debian image on an SDcard. But it looks like the SDcard uboot tries to read the eMMC content. Is there a way to bypass that?

**Comment by RobertCNelson** [comment]
@woopla 

Hold down the "boot" button, and insert power cable.

Regards,

**Comment by woopla** [comment]
@RobertCNelson that's what I've been doing already :( Now that I renamed MLO on the eMMC I don't even have to do that since it'll start the SDcard U-Boot directly - I just tried both, and got the same output (first with the button pressed, then without):
```shell
U-Boot SPL 2019.01-00002-g6de8c74429 (Apr 10 2019 - 15:14:57 -0500)
Trying to boot from MMC1
Loading Environment from EXT4... ** No partition table - mmc 0 **

U-Boot SPL 2019.01-00002-g6de8c74429 (Apr 10 2019 - 15:14:57 -0500)
Trying to boot from MMC1
Loading Environment from EXT4... ** No partition table - mmc 0 **
```

Looks like it's able to find the SPL in the first sectors of the SDcard just fine, but fails to point to the SDcard for the rest...

**Comment by RobertCNelson** [comment]
okay, this is something else..  u-boot stuck in SPL.. either it's a bad eeprom, or something else..

Does the Debian 9.5 2018-10-07 image from here load?

http://beagleboard.org/latest-images

If it does, can you grab the output of:

sudo /opt/scripts/tools/version.sh

Regards,

**Comment by woopla** [comment]
Slightly different behavior:

1. If I do not press the boot button, it displays a C every half-second or so, as if I had not inserted the SDcard (with MLO renamed on the eMMC, there's nothing to boot to):
```shell
CCCCCCCCCCCCCCCCCCCCCC
```

2. If I press the boot button, I'm getting this again (with the different U-Boot SPL version):
```shell
U-Boot SPL 2018.09-00002-g0b54a51eee (Sep 10 2018 - 19:41:39 -0500)
Trying to boot from MMC1
Loading Environment from EXT4... ** No partition table - mmc 0 **
```

Thanks,

Clément

**Comment by RobertCNelson** [comment]
I know this seems like random, because it is, how about:

https://debian.beagleboard.org/images/bone-debian-8.6-iot-armhf-2016-12-09-4gb.img.xz

Regards,

**Comment by woopla** [comment]
Different error message:
```shell
U-Boot SPL 2016.11-00002-gab8be1c (Dec 07 2016 - 12:54:09)
Trying to boot from MMC1
** First descriptor is NOT a primary desc on 0:1 **
```

That's progress :)

Cheers,

Clément

**Comment by RobertCNelson** [comment]
@woopla yeah closer, let's try:

https://debian.beagleboard.org/images/bone-debian-8.3-lxqt-4gb-armhf-2016-01-24-4gb.img.xz

(it's first debian 8.x image) fingers crossed, don't really want to try the 7.x family...

Regards,

**Comment by woopla** [comment]
Sorry @RobertCNelson, no luck either (different message though):
```shell
U-Boot SPL 2016.01-00001-g4eb802e (Jan 13 2016 - 11:14:31)
Trying to boot from MMC
bad magic
bad magic
SPL: failed to boot from all boot devices
### ERROR ### Please RESET the board ###
```

Is this a case of 'you need to update the eMMC before you can boot something recent'? In that case, isn't there a way to completely bypass whatever is on the eMMC?

Thanks,

Clément

**Comment by RobertCNelson** [comment]
@woopla holding down the boot button will bypass the eMMC..

What about the original image?

https://debian.beagleboard.org/images/bone-debian-7.5-2014-05-14-2gb.img.xz

Regards,

**Comment by woopla** [comment]
@RobertCNelson it's complaining in a different way:
```shell
U-Boot SPL 2014.04-00014-g47880f5 (Apr 22 2014 - 13:23:54)
** Partition 1 not valid on device 0 **
spl_register_fat_device: fat register err - -1
### ERROR ### Please RESET the board ###
```

Running the Angstrom image https://s3.amazonaws.com/angstrom/demo/beaglebone/Angstrom-Cloud9-IDE-GNOME-eglibc-ipk-v2012.12-beaglebone-2013.06.20.img.xz yields this:

```shell
U-Boot SPL 2013.04-dirty (Jun 19 2013 - 09:57:14)
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Peripheral mode controller at 47401000 using PIO, IRQ 0
musb-hdrc: ConfigData=0xde (UTMI-8, dyn FIFOs, HB-ISO Rx, HB-ISO Tx, SoftConn)
musb-hdrc: MHDRC RTL version 2.0 
musb-hdrc: setup fifo_mode 4
musb-hdrc: 28/31 max ep, 16384/16384 memory
USB Host mode controller at 47401800 using PIO, IRQ 0
OMAP SD/MMC: 0
** Partition 1 not valid on device 0 **
spl: fat register err - -1
### ERROR ### Please RESET the board ###
```

I'm perplexed by all the messages mentioning device 0 (or 'Trying to boot from MMC' on the previous comment) on pretty much all the images I tried, hence my question regarding the eMMC bypass... Isn't there something fishy here?

Thanks,

Clément

**Comment by fabiogonsalves** [comment]
Hi! I have done as you told me, using balena etcher.
ult was different, but still not successful...

[image: image.png]

Fabio gonçalves ***@***.***> escreveu no dia sábado,
23/10/2021 à(s) 00:52:
